<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class RubricEntry extends Model
{
    use HasFactory;

    public function delete()
    {
        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function rubric()
    {
        return $this->belongsTo('App\Models\Rubric', 'rubric_id');
    }
}
